name: loud_question
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  another_flushbar: ^1.12.29
  bloc_concurrency: ^0.2.1
  cupertino_icons: ^1.0.5
  dio: ^5.0.2
  envied: ^0.3.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  flutter_hooks: ^0.18.6
  fpdart: ^0.5.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^6.2.0
  injectable: ^2.1.0
  json_annotation: ^4.8.0
  logging: ^1.1.1
  problem_details: ^0.0.2
  retrofit: ^4.0.1
  rxdart: ^0.27.7
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.1
  retrofit_generator: ^6.0.0+1

flutter:
  uses-material-design: true
